// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: telemetry/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TelemetryService_SubmitTelemetry_FullMethodName      = "/telemetry.TelemetryService/SubmitTelemetry"
	TelemetryService_SubmitTelemetryBatch_FullMethodName = "/telemetry.TelemetryService/SubmitTelemetryBatch"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	SubmitTelemetry(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_SubmitTelemetryClient, error)
	SubmitTelemetryBatch(ctx context.Context, in *TelemetryBatchRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) SubmitTelemetry(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_SubmitTelemetryClient, error) {
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], TelemetryService_SubmitTelemetry_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceSubmitTelemetryClient{stream}
	return x, nil
}

type TelemetryService_SubmitTelemetryClient interface {
	Send(*TelemetryData) error
	CloseAndRecv() (*TelemetryResponse, error)
	grpc.ClientStream
}

type telemetryServiceSubmitTelemetryClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceSubmitTelemetryClient) Send(m *TelemetryData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *telemetryServiceSubmitTelemetryClient) CloseAndRecv() (*TelemetryResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TelemetryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telemetryServiceClient) SubmitTelemetryBatch(ctx context.Context, in *TelemetryBatchRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_SubmitTelemetryBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	SubmitTelemetry(TelemetryService_SubmitTelemetryServer) error
	SubmitTelemetryBatch(context.Context, *TelemetryBatchRequest) (*TelemetryResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) SubmitTelemetry(TelemetryService_SubmitTelemetryServer) error {
	return status.Errorf(codes.Unimplemented, "method SubmitTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) SubmitTelemetryBatch(context.Context, *TelemetryBatchRequest) (*TelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTelemetryBatch not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_SubmitTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).SubmitTelemetry(&telemetryServiceSubmitTelemetryServer{stream})
}

type TelemetryService_SubmitTelemetryServer interface {
	SendAndClose(*TelemetryResponse) error
	Recv() (*TelemetryData, error)
	grpc.ServerStream
}

type telemetryServiceSubmitTelemetryServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceSubmitTelemetryServer) SendAndClose(m *TelemetryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *telemetryServiceSubmitTelemetryServer) Recv() (*TelemetryData, error) {
	m := new(TelemetryData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TelemetryService_SubmitTelemetryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).SubmitTelemetryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_SubmitTelemetryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).SubmitTelemetryBatch(ctx, req.(*TelemetryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTelemetryBatch",
			Handler:    _TelemetryService_SubmitTelemetryBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitTelemetry",
			Handler:       _TelemetryService_SubmitTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry/telemetry.proto",
}
