// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pricing/pricing.proto

package pricing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PricingService_CalculatePrice_FullMethodName     = "/pricing.PricingService/CalculatePrice"
	PricingService_GetPriceEstimate_FullMethodName   = "/pricing.PricingService/GetPriceEstimate"
	PricingService_GetPricingRules_FullMethodName    = "/pricing.PricingService/GetPricingRules"
	PricingService_UpdatePricingRules_FullMethodName = "/pricing.PricingService/UpdatePricingRules"
)

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PricingServiceClient interface {
	CalculatePrice(ctx context.Context, in *CalculatePriceRequest, opts ...grpc.CallOption) (*CalculatePriceResponse, error)
	GetPriceEstimate(ctx context.Context, in *GetPriceEstimateRequest, opts ...grpc.CallOption) (*GetPriceEstimateResponse, error)
	GetPricingRules(ctx context.Context, in *GetPricingRulesRequest, opts ...grpc.CallOption) (*GetPricingRulesResponse, error)
	UpdatePricingRules(ctx context.Context, in *UpdatePricingRulesRequest, opts ...grpc.CallOption) (*UpdatePricingRulesResponse, error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) CalculatePrice(ctx context.Context, in *CalculatePriceRequest, opts ...grpc.CallOption) (*CalculatePriceResponse, error) {
	out := new(CalculatePriceResponse)
	err := c.cc.Invoke(ctx, PricingService_CalculatePrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) GetPriceEstimate(ctx context.Context, in *GetPriceEstimateRequest, opts ...grpc.CallOption) (*GetPriceEstimateResponse, error) {
	out := new(GetPriceEstimateResponse)
	err := c.cc.Invoke(ctx, PricingService_GetPriceEstimate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) GetPricingRules(ctx context.Context, in *GetPricingRulesRequest, opts ...grpc.CallOption) (*GetPricingRulesResponse, error) {
	out := new(GetPricingRulesResponse)
	err := c.cc.Invoke(ctx, PricingService_GetPricingRules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingServiceClient) UpdatePricingRules(ctx context.Context, in *UpdatePricingRulesRequest, opts ...grpc.CallOption) (*UpdatePricingRulesResponse, error) {
	out := new(UpdatePricingRulesResponse)
	err := c.cc.Invoke(ctx, PricingService_UpdatePricingRules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
// All implementations must embed UnimplementedPricingServiceServer
// for forward compatibility
type PricingServiceServer interface {
	CalculatePrice(context.Context, *CalculatePriceRequest) (*CalculatePriceResponse, error)
	GetPriceEstimate(context.Context, *GetPriceEstimateRequest) (*GetPriceEstimateResponse, error)
	GetPricingRules(context.Context, *GetPricingRulesRequest) (*GetPricingRulesResponse, error)
	UpdatePricingRules(context.Context, *UpdatePricingRulesRequest) (*UpdatePricingRulesResponse, error)
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPricingServiceServer struct {
}

func (UnimplementedPricingServiceServer) CalculatePrice(context.Context, *CalculatePriceRequest) (*CalculatePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePrice not implemented")
}
func (UnimplementedPricingServiceServer) GetPriceEstimate(context.Context, *GetPriceEstimateRequest) (*GetPriceEstimateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriceEstimate not implemented")
}
func (UnimplementedPricingServiceServer) GetPricingRules(context.Context, *GetPricingRulesRequest) (*GetPricingRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPricingRules not implemented")
}
func (UnimplementedPricingServiceServer) UpdatePricingRules(context.Context, *UpdatePricingRulesRequest) (*UpdatePricingRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePricingRules not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}

// UnsafePricingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServiceServer will
// result in compilation errors.
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_CalculatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).CalculatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_CalculatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).CalculatePrice(ctx, req.(*CalculatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_GetPriceEstimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetPriceEstimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetPriceEstimate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetPriceEstimate(ctx, req.(*GetPriceEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_GetPricingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPricingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetPricingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_GetPricingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetPricingRules(ctx, req.(*GetPricingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingService_UpdatePricingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePricingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).UpdatePricingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingService_UpdatePricingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).UpdatePricingRules(ctx, req.(*UpdatePricingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingService_ServiceDesc is the grpc.ServiceDesc for PricingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricing.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePrice",
			Handler:    _PricingService_CalculatePrice_Handler,
		},
		{
			MethodName: "GetPriceEstimate",
			Handler:    _PricingService_GetPriceEstimate_Handler,
		},
		{
			MethodName: "GetPricingRules",
			Handler:    _PricingService_GetPricingRules_Handler,
		},
		{
			MethodName: "UpdatePricingRules",
			Handler:    _PricingService_UpdatePricingRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing/pricing.proto",
}
